config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :shops, except: :destroy do
    resources :bookmarks, only: :create
    resources :reviews, only: [:new, :create, :index]
  end
  resources :bookmarks, only: [:index, :destroy]
  delete 'bookmarks/:id/d', to: 'bookmarks#destroy_fresh', as: :destroy_fresh
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  validates :rating, presence: true, inclusion: { in: (1..5).to_a }
  # validates :user_id, uniqueness: { scope: :review_id }
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos
  validates :name, presence: true
  # include PgSearch::Model
  # pg_search_scope :search_by_name_and_details,
  #   against: [:name, :address, :details],
  #   using: {
  #     tsearch: { prefix: true }
  #   }
  def set_rating
    reviews = self.reviews
    total = 0
    reviews.each do |review|
      total += review.rating
    end
    average = total / reviews.count.to_f.round(1)
    unless average.nan?
      self.rating = average
    else
      self.rating = 1.0
    end
    self.rating = 1.0 if self.rating.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookmarks
  has_many :reviews
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :show], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @shop = Shop.find(params[:shop_id])
    @review.shop = @shop
  end

  def create
    @review = Review.new(review_params)
    @shop = Shop.find(params[:shop_id])
    @review.shop = @shop
    @review.user = current_user
    authorize @review
    @shop.set_rating
    @review.save
    redirect_to shop_path(@shop)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @shops = policy_scope(Shop)
    @shops = Shop.all
    @shops.each do |shop|
    end
    @markers = @shops.geocoded.map do |shop|
      {
        lat: shop.latitude,
        lng: shop.longitude,
        info_window: render_to_string(partial: "info_window", locals: { shop: shop })
      }
    end
    if params[:query].present?
      @shops = @shops.search_by_name_and_details(params[:query])
      @shops.each do |p|
        p.set_rating
      end
      @markers = @shops.geocoded.map do |shop|
      {
        lat: shop.latitude,
        lng: shop.longitude,
        info_window: render_to_string(partial: "info_window", locals: { shop: shop })
      }
      end
      @shops = @shops.sort_by(&:rating).reverse
    else
      @shops = @shops.sort_by(&:rating).reverse
    end
  end

  def show
    @shops = policy_scope(Shop)
    @review = Review.new
    @shop = Shop.find(params[:id])
    @reviews = @shop.reviews
    @shop_arr = []
    @shop_arr << @shop
    @markers = @shop_arr.map do |shop|
      {
        lat: shop.latitude.nil? ? 59.3354662 : shop.latitude,
        lng: shop.longitude.nil? ? 18.0600026 : shop.longitude,
        info_window: render_to_string(partial: "info_window", locals: { shop: shop })
      }
    end
    @favorite = is_favorite?(@shop.id)
    @shop.set_rating
    @user = current_user
  end

  def new
    @shop = Shop.new
    authorize @shop
  end

  def create
    @shop = Shop.new(shop_params)
    authorize @shop
    if @shop.save
      redirect_to shop_path(@shop)
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    authorize @shop
  end

  def update
    @shop = Shop.find(params[:id])
    authorize @shop
    @shop.update(shop_params)
    redirect_to shop_path(@shop)
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :address, :region, :details, photos: [])
  end

  def is_favorite?(id)
    @user = current_user
    return false if @user == nil
    @bookmark = @user.bookmarks.where(:shop_id => id).last
    return @bookmark.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta property="fb:app_id" content="<%= meta_title %>" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <style>@import url('https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500&display=swap');</style>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/navbar-mobile' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( <%= image_path "bubblet.jpg" %>);">
  <div class="home-container">
    <h1 class="py-3">Love bubble tea? So do we!</h1>
    <p class="py-3">That's why we made it easy for you to find your new fave.</p>
  </div>
  <div class="home-container">
    <div class="home-buttons">
      <%= link_to "Get started", shops_path, class: "btn btn-city" %>
    </div>
  </div>
</div>

app/views/reviews/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title w-100 text-center" id="exampleModalLabel"><%= @shop.name %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@shop, @review] do |f| %>
          <%= f.input :rating, collection: (1..5).to_a, label:false %>
          <%= f.input :content, label: "My review:" %>
          <%= f.submit "Submit", class: "btn btn-form w-100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-between align-items-center">
  <div class="d-flex justify-content-right align-items-center p-2">
    <p id="footer-left">Made with <i class="fas fa-heart"></i> by Joseph Rohde</p>
  </div>
  <div class="footer-socials p-2">
    <a href="https://github.com/DittoJoe" target="blank"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/joseph-james-rohde/" target="blank"><i class="fab fa-linkedin"></i></a>
    <a href="mailto: info@bubblehe.art" target="blank"><i class="fas fa-envelope"></i></a>
  </div>
</div>

app/views/shared/_navbar-mobile.html.erb
<div class="navbar navbar-mobile desktop-hide">
  <div class="footer-buttons">
    <div class="footer-icon">
      <div class="avatar">
        <%= link_to new_user_session_path do %>
          <%= far_icon "calendar-plus" %>
        <% end %>
      </div>
    </div>
    <p class="footer-text">Add new</p>
  </div>
  <div class="footer-buttons">
    <div class="footer-icon">
      <div class="avatar">
        <%= link_to new_user_session_path do %>
          <%= far_icon "heart" %>
        <% end %>
        </div>
      </div>
    <p class="footer-text">My hearts</p>
  </div>
  <div class="footer-buttons">
    <div class="footer-icon">
      <div class="avatar">
        <%= link_to new_user_session_path do %>
          <%= far_icon "eye" %>
        <% end %>
      </div>
    </div>
    <p class="footer-text">Explore</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-bubble">
  <%= link_to "/", class: "navbar-brand" do %>
    <h1 class="shopn">bubble<strong>heart</strong></h1>
  <% end %>
  <button class="navbar-toggler mobile-hide" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon mobile-hide"></span>
  </button>
  <div class="collapse navbar-collapse mobile-hide" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mobile-hide">
      <% if user_signed_in? %>
        <li class="nav-item mobile-hide">
          <%= link_to "Explore", shops_path, class: "nav-link un mobile-hide" %>
        </li>
        <li class="nav-item dropdown mobile-hide">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle mobile-hide", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right mobile-hide" aria-labelledby="navbarDropdown">
            <%= link_to "Add a shop", new_shop_path, class: "dropdown-item mobile-hide" %>
            <%= link_to "My Hearts", bookmarks_path(@bookmarks), class: "dropdown-item mobile-hide" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item mobile-hide" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item mobile-hide">
          <%= link_to "Login", new_user_session_path, class: "nav-link mobile-hide" %>
        </li>
      <% end %>
      <div class="avatar mobile-hide">
        <%= link_to new_user_session_path do %>
          <%= far_icon "heart" %>
        <% end %>
      </div>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search-bar">
  <%= form_tag shops_path, method: :get do %>
  <div class="d-flex search_bar">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a shop"
      %>
   <%= submit_tag "Search", class: "btn btn-city w-25" %></div>
  <% end %>
</div>

app/views/shops/_info_window.html.erb
<h3><%= link_to shop.name, shop_path(shop) %></h3>

app/views/shops/_rating.html.erb
<div class="rating">
  <i class="fas fa-star"></i>
  <% if @rating < 1.5 %>
    <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 2 %>
    <i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 2.5 %>
    <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 3 %>
    <i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 3.5 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 4 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i>
  <% elsif @rating < 4.5 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 5.0 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i>
  <% elsif @rating == 5.0 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
  <% else %>
    <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% end %>
</div>

app/views/shops/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( <%= image_path "bubblet.jpg" %>);">
  <div id="create" class="container create-form col-10 col-offset-3 py-3 px-4">
    <div id="create-form">
      <h2 id="form-title">Edit shop</h2>
      <%= simple_form_for(@shop) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :details %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: "btn btn-form w-100" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="show-container">
  <div class="container">
    <div class="srch">
      <%= render 'shared/search' %>
      <div class="search-bar"></div>
    </div>
    <div class="cards-index">
      <% @shops.each do |shop| %>
        <%= link_to shop_path(shop) do %>
          <div class="card-shop">
            <% if shop.photos.attached? %>
              <%= cl_image_tag shop.photos.first.key %>
            <% else %>
              <%= image_tag "https://icon-library.net/images/free-bike-icon/free-bike-icon-8.jpg" %>
            <% end %>
              <div class="card-shop-infos">
                <h2><%= shop.name %></h2>
                <% shop.set_rating %>
                <% @rating = shop.rating %>
                <%= render 'rating' %>
              </div>
           </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="container p-2 mobile-hide">
    <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( <%= image_path "bubblet.jpg" %>);">
  <div id="create" class="container create-form col-10 col-offset-3 py-3 px-4">
    <div id="create-form">
      <h2 id="form-title">Add a shop</h2>
      <%= simple_form_for(@shop) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :details %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: "btn btn-form w-100" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/show.html.erb
<div class="container text-center pt-3">
  <h1><%= @shop.name %></h1>
</div>
  <div class="show-container">
    <div>
    <div class="card-show">
      <% if @shop.photos.attached? %>
        <%= cl_image_tag @shop.photos.first.key %>
      <% else %>
        <%= image_tag "bubblet.jpg" %>
      <% end %>
      <div class="card-show-infos">
        <div data-controller="like" data-like-target="link" data-shop="<%= @shop.id %>" data-bookmark="<%= Bookmark.find_by(user: current_user, shop: @shop).id if Bookmark.find_by(user: current_user, shop: @shop)%>">
          <% unless @favorite %>
              <i class="far fa-heart empty-heart favorite" data-action="click->like#create"></i>
          <% else %>
              <i class="fas fa-heart full-heart favorite" data-action="click->like#delete"  data-bookmark="<%= @bookmark.id %>"></i>
          <% end %>
        </div>
        <% @rating = @shop.rating %>
        <%= render 'rating' %>
        <div>
          <h3><%= @shop.details %></h3>
          <button type="button" class="btn btn-form" data-toggle="modal" data-target="#exampleModal">Add a review</button>
          <%= render 'reviews/modal' %>
        </div>
      </div>
    </div>
    <div class="review-container">
      <h1>Reviews</h1>
      <% @reviews.reverse.each do |review| %>
        <div class="card-review">
          <div class="review-rating">
            <i class="fas fa-star"></i>
            <% @rating = review.rating %>
            <% if @rating < 1.5 %>
              <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating < 2.5 %>
              <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating < 3.5 %>
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating < 4.5 %>
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating == 5.0 %>
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
            <% else %>
              <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% end %>
          </div>
          <div class="avatar-img">
            <% if review.user.avatar.attached? %>
              <%= cl_image_tag review.user.avatar.key, class: "avatar-review" %>
            <% else %>
              <%= image_tag "https://i.pravatar.cc/150?img=13", class: "avatar-review" %>
            <% end %>
          </div>
          <div class="card-review-text">
            <span id="review-name"><%= review.user.username %></span>
            <span id="review-time"><%= review.created_at.strftime("%a %b %e") %></span>
            <p><%= review.content %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>